// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_404.tsx';
import * as $1 from './routes/_app.tsx';
import * as $2 from './routes/about/index.tsx';
import * as $3 from './routes/index.tsx';
import * as $4 from './routes/tag/[tag].tsx';

const manifest = {
  routes: {
    './routes/_404.tsx': $0,
    './routes/_app.tsx': $1,
    './routes/about/index.tsx': $2,
    './routes/index.tsx': $3,
    './routes/tag/[tag].tsx': $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
